version: '3'
services:
  app:
    container_name: wa-gateway-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5001"
    volumes:
      - .:/app
    # environment:
    #   - NODE_ENV=production
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "215M"

networks:
  default:
    name: localhost
    external: true