version: '3'
services:
  app:
    container_name: wa-gateway-api
    build: .
    ports:
      - "5555:5001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      resources:
        limits:
          cpu: "0.25"
          memory: "215M"
        reservations:
          cpu: "0.50"
          memory: "512M"
